const PASSWORD="DEO";
// COLLEZ ICI LE LIEN DE VOTRE GROUPE WHATSAPP
const WHATSAPP_LINK="COLLEZ-ICI-LE-LIEN-DU-GROUPE";
const members=[
["Déo Vumilia Buuma","Père","26/12/1972","Père de la famille, gradué en sciences de l'éducation et enseignant dans une école secondaire."],["Sirire Masirika Francine","Mère","01/03/1978","Mère de la famille, commerçante et cultivatrice."],["Ameshinda Vumilia Alliance","Fils aîné — décédé","03/11/1996","Fils aîné de la famille. Il est décédé célibataire, après avoir atteint le niveau de Bac 2 en management. Que son âme repose en paix."],["Salama Namwangasa Yvette","2e enfant — fille","14/07/2000","Infirmière, graduée de l'Institut Supérieur des Techniques Médicales de Bukavu. Elle est mariée à Justin Ushindi."],["Buuma Vumilia Benjamin","3e fils","10/05/2002","Laborantin, licencié en laboratoire de l'Institut Supérieur des Techniques Médicales de Bukavu."],["ATUKUZWE Vumilia Jonathan","4e fils","22/05/2005","Informaticien, licencié de l'Institut Supérieur Pédagogique de Bukavu."],["Basimire Vumilia Moïse","5e fils","18/09/2007","Économiste, licencié de l'Université Officielle de Bukavu."],["Barikiwa Vumilia Angélique","6e fille","20/03/2010","Commercialiste de l'Institut Kando."],["Bwaashi Vumilia Gloire","7e fils","16/09/2012","Commercialiste de l'Institut Kando."],["Chisiki Vumilia Bien-aimé","8e fils","16/10/2014","Histoire à compléter…"],["Furaha Vumilia Noela","9e fille","26/12/2016","Histoire à compléter…"],["Asifiwe Vumilia Victoire","10e enfant — fils, cadet","07/07/2018","Cadet de la famille."]];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function login(){if(document.getElementById("pw").value===PASSWORD){document.getElementById("login").style.display="none";document.getElementById("site").style.display="block";document.getElementById("logout").style.display="block";render()}else document.getElementById("error").style.display="block"}function logout(){location.reload()}
function render(){document.getElementById("members").innerHTML=members.map(m=>`<div class="member"><h3>${esc(m[0])}</h3><b>${esc(m[1])}</b> — ${esc(m[2])}<p>${esc(m[3])}</p></div>`).join("");renderPhotos();const w=document.getElementById("wa");if(WHATSAPP_LINK.startsWith("https://"))w.href=WHATSAPP_LINK;else w.onclick=e=>{e.preventDefault();alert("Ajoutez le lien WhatsApp dans script.js.")}}
function renderPhotos(){const a=JSON.parse(localStorage.getItem("familyPhotos")||"[]");document.getElementById("photos").innerHTML=a.map((p,i)=>`<div class="photo"><img src="${p.data}"><button onclick="delPhoto(${i})">×</button><small>${esc(p.caption||"Souvenir de famille")}</small></div>`).join("")}
function addPhotos(){const fs=[...document.getElementById("files").files],cap=document.getElementById("caption").value,a=JSON.parse(localStorage.getItem("familyPhotos")||"[]");if(!fs.length)return alert("Choisissez une photo.");let n=fs.length;fs.forEach(f=>{let r=new FileReader;r.onload=e=>{a.push({data:e.target.result,caption:cap});if(--n===0){localStorage.setItem("familyPhotos",JSON.stringify(a));renderPhotos()}};r.readAsDataURL(f)})}function delPhoto(i){let a=JSON.parse(localStorage.getItem("familyPhotos")||"[]");a.splice(i,1);localStorage.setItem("familyPhotos",JSON.stringify(a));renderPhotos()}document.getElementById("pw").addEventListener("keydown",e=>{if(e.key==="Enter")login()});
